# Generated by Django 2.1.7 on 2019-04-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo_Entero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributo_Float',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Atributo_String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('dominio', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_caso', models.FileField(upload_to='')),
                ('modelo_generado', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='clasificador',
            field=models.ManyToManyField(to='modelos.Clasificador'),
        ),
        migrations.AddField(
            model_name='atributo_string',
            name='caso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.Caso'),
        ),
        migrations.AddField(
            model_name='atributo_float',
            name='caso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.Caso'),
        ),
        migrations.AddField(
            model_name='atributo_entero',
            name='caso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.Caso'),
        ),
    ]
