# Generated by Django 2.1.7 on 2019-04-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='clasificador',
        ),
        migrations.AddField(
            model_name='caso',
            name='clasificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelos.Clasificador'),
        ),
    ]
