# Generated by Django 2.1.7 on 2019-04-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20190416_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.DataSet'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(null=True, upload_to='datasets'),
        ),
    ]
