# Generated by Django 2.1.7 on 2019-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('algoritmo', models.CharField(max_length=20)),
                ('dataSet', models.CharField(max_length=20)),
                ('TiposDatos', models.CharField(max_length=50)),
            ],
        ),
    ]
