# Generated by Django 2.1.7 on 2019-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLAApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('atributos', models.CharField(choices=[('clase', 'clase'), ('atributo', 'atributo'), ('algoritmo', 'algoritmo')], max_length=10)),
            ],
        ),
    ]
